### ISSUE TITLE
Instructions do not work for latest version

### ISSUE THREAD

**Issue by cgnaughton** [Dhyfer1/Dracula-for-EverythingToolbar#2]
The most recent version of EverythingToolbar does not work with these instructions.

**Comment by Dhyfer1** [comment]
You're right. Everythingtoolbar has changed, as well as the locations of the files. This week I will dedicate myself again to reviewing my theme. 

May I know which version of Windows (10 or 11) it is not working on? Because when I created the theme I made it for Windows 10, I haven't adapted my theme for Windows 11 yet, but I will.

**Comment by cgnaughton** [comment]
I am on Windows 11, Clean Install. I know there are some differences
between Windows 11 installed on top of Windows 10 vs Windows 11 clean
install, not sure if it will make a difference or not.
I really appreciate, I a love the dracula theming and appreciate all the
work all the authors have done.

Thanks,

Christopher G. Naughton

May those who love us, love us.
For those who don't, may God turn their hearts.
And if he cannot turn their hearts.
May He turn their ankles so we may know them by their limping.

--Irish Proverb (author unknown)

http://blog.cnaughton.com

**Comment by Dhyfer1** [comment]
I have already updated my theme for Windows 11, I hope you like it. I have also updated the INSTALL.md file with new instructions for installing both themes.

Now all that's left is for the site https://draculatheme.com/everythingtoolbar to be updated with the new instructions. In the meantime, you can see the updated instructions in the [INSTALL.md](https://github.com/dracula/everythingtoolbar/blob/master/INSTALL.md) file

**Comment by cgnaughton** [comment]
Awesome, thanks for the update!

Christopher G. Naughton

May those who love us, love us.
For those who don't, may God turn their hearts.
And if he cannot turn their hearts.
May He turn their ankles so we may know them by their limping.

--Irish Proverb (author unknown)

http://blog.cnaughton.com

**Comment by Dhyfer1** [comment]
You're welcome. 👍

Enjoy my theme, if you think something is missing just let me know. 

I think that's all, I can now close this issue.
Good day!
